spring.application.name=backend
server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gik}
spring.datasource.username=${DB_USERNAME:gik}
spring.datasource.password=${DB_PASSWORD:gik}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

mybatis.mapper-locations=classpath*:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-fetch-size=100

spring.jackson.default-property-inclusion=non_null

auth.jwt.secret=${AUTH_JWT_SECRET:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}
auth.jwt.expiration-seconds=${AUTH_JWT_EXPIRATION_SECONDS:315360000}
auth.google.client-ids=${AUTH_GOOGLE_CLIENT_IDS:314100642419-7uo18h9c4e8je9a4g34118eu97k7itgm.apps.googleusercontent.com,314100642419-i7epqv2gemvl0chq6ab249kidpfa5d55.apps.googleusercontent.com,314100642419-o22kfuutrrja23kdmqv3f54reca1htnm.apps.googleusercontent.com}
auth.apple.client-id=${AUTH_APPLE_CLIENT_ID:}
